# Generated by Django 3.0.8 on 2021-02-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryItem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryitem',
            name='costPrice',
        ),
        migrations.RemoveField(
            model_name='bakeryitem',
            name='sellingPrice',
        ),
    ]
