# Generated by Django 3.0.8 on 2021-02-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryItem', '0002_auto_20210219_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='value',
            new_name='description',
        ),
    ]
