# Generated by Django 3.0.8 on 2021-02-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bakeryItem', '0003_auto_20210219_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costPrice', models.FloatField()),
                ('sellingPrice', models.FloatField()),
                ('bakeryitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakeryItem.BakeryItem')),
            ],
        ),
    ]
