# Generated by Django 3.0.8 on 2021-02-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='qty',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
