# Generated by Django 3.0.8 on 2021-02-19 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryItem', '0003_auto_20210219_1618'),
        ('order', '0002_auto_20210220_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakeryItem.BakeryItem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1, message='minimum 1 qty is mst include')]),
        ),
    ]
