# Generated by Django 3.0.8 on 2021-02-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210220_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='inventory',
            new_name='bakeryItem',
        ),
    ]
